# A sample Gemfile
# source "https://rubygems.org"
source "http://ruby.taobao.org"

ruby '1.9.3'


gem "sinatra", '1.4.5'
gem "sinatra-reloader"
gem 'redcarpet'
gem "thin", '1.6.2'
#gem 'pry'
#gem 'pry-doc'
